### ISSUE TITLE
tradeEthForExactTokensWithData for last tokens

### ISSUE THREAD

**Issue by tarrencev** [Uniswap/uniswap-v2-sdk#12]
I'm working on an application that leverages uniswap exchanges. Our ERC20 tokens have 0 decimals. I'm running into an issue when purchasing the last token in the exchange.

When calling `tradeEthForExactTokensWithData` to purchase the last tokens in an exchange, an error is thrown here https://github.com/Uniswap/uniswap-sdk/blob/1fcc0a59cd960e4ed0465c7714557688c01b31fe/src/computation/trade.ts#L38-L52
```
Uncaught Error: Passed bigNumber 'Infinity' is not a valid uint256.
```

This is because denominator becomes 0 and inputAmount is then divided by 0. 
https://github.com/Uniswap/uniswap-sdk/blob/1fcc0a59cd960e4ed0465c7714557688c01b31fe/src/computation/trade.ts#L46-L47

Is it possible to support this use case or should the exchange always have remaining tokens in it?

Is seems the js logic mirrors the vyper logic [here](https://github.com/Uniswap/contracts-vyper/blob/c10c08d81d6114f694baa8bd32f555a40f6264da/contracts/uniswap_exchange.vy#L124), although im not sure how vyper handles division by zero.

**Comment by moodysalem** [comment]
V1 SDK will no longer be updated
https://github.com/Uniswap/uniswap-v1-sdk
