### ISSUE TITLE
Not persistent documentetion

### ISSUE THREAD

**Issue by Npizza** [Uniswap/uniswap-v2-sdk#28]
I am trying to recreate the example froom the SDK docs here: https://uniswap.org/docs/v2/javascript-SDK/fetching-data/
and I get this error:

![image](https://user-images.githubusercontent.com/25034947/87229705-1cebd000-c3b3-11ea-9894-16b520659cbb.png)

![image](https://user-images.githubusercontent.com/25034947/87229710-2e34dc80-c3b3-11ea-8411-3f2f6de34dfb.png)

Can someone help me?
Thank you!

**Comment by moodysalem** [comment]
Symptom of https://github.com/Uniswap/uniswap-v2-sdk/issues/29
