### ISSUE TITLE
Issue with "yarn add @uniswap/sdk"

### ISSUE THREAD

**Issue by About7Sharks** [Uniswap/uniswap-v2-sdk#33]
Hi there, I'm doing some prototyping with a bare bones vite project and the command "yarn add @uniswap/sdk" listed [here](https://uniswap.org/docs/v2/javascript-SDK/quick-start) seems to cause  an error when running "yarn dev".

**Error Message**
``` 
[vite] Dep optimization failed with error:
[vite]: Rollup failed to resolve import "@ethersproject/address" from "node_modules/@uniswap/sdk/dist/sdk.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
```

**Solution**
So my solution was to go into package.json and link to this repo directly 
```
 "dependencies": {
    "@uniswap/sdk": "git+https://github.com/Uniswap/uniswap-sdk.git",
    "vue": "^3.0.0-rc.1"
  },
```
After running yarn install the development sever was able to startup properly. 

**Steps to reproduce**
```
yarn create vite-app testuniswap
cd testuniswap
yarn
yarn add @uniswap/sdk
yarn dev
```

**Comment by MikeBailleul** [comment]
@About7Sharks I got the same issue, I tried adding _**"@uniswap/sdk": "git+https://github.com/Uniswap/uniswap-sdk.git"**_ in the dependencies like you did, but I still get an error:

` Cannot find module 'node_modules/@uniswap/sdk/dist/index.js'. Please verify that the package.json has a valid "main" entry
`

Any idea why?

**Comment by MikeBailleul** [comment]
Okay the original issue is actually a missing peer dependency. To solve it, just add it:

`yarn add ethers`

**Comment by stoplion** [comment]
Same issue, adding `ethers` fixed it.
