### ISSUE TITLE
How to connect the wallet?

### ISSUE THREAD

**Issue by mukedian0** [Uniswap/uniswap-v2-sdk#36]
The first step to use these APIs should be to connect the wallet, otherwise how to trade? But I didn't find a way to connect the wallet, thank you.

**Comment by benjyz** [comment]
I think the docs are missing a step... without setup getting the error 
`node_modules/@ethersproject/providers/lib/base-provider.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.
`

**Comment by pawpawclaw** [comment]
should use walletconnect set providers etc i rekon

**Comment by moodysalem** [comment]
This SDK does not provide the ability to connect a wallet, it just gives you some utility classes and methods to construct a valid trade in Uniswap. Signing the transaction is the responsibility of the user. In addition, the responsibility of fetching the pair data from the network is not handled in this library

See https://github.com/Uniswap/uniswap-v2-sdk/issues/39#issuecomment-792328760
