### ISSUE TITLE
ethersproject base-provider error

### ISSUE THREAD

**Issue by benjyz** [Uniswap/uniswap-v2-sdk#38]
trying to run example code. since the docs are missing a step for setting up provider not sure how to solve this. I think this part is not very clear: https://uniswap.org/docs/v2/SDK/getting-started/#dependencies

`node_modules/@ethersproject/providers/lib/base-provider.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node'.`

**Comment by LearnPHPaz** [comment]
I'm trying to use my own ethers api key to create the provider but I can't find how to do it, it's not in the documentation. Could someone help? If i find how to do it i'll post it here.

**Comment by dahifi** [comment]
@LearnPHPaz did you figure it out? The Ether's documentation shows how to call the provider API calls (https://docs.ethers.io/v5/api-keys/), and it looks like the provider call is made here, (https://github.com/Uniswap/uniswap-sdk/blob/a88048e9c4198a5bdaea00883ca00c8c8e582605/src/fetcher.ts#L38), so you could edit that directly in the source code. 

I'm not sure to do it correctly though.

**Comment by dahifi** [comment]
Issue was referenced here: https://github.com/Uniswap/uniswap-sdk/issues/37

Additional documentation here: https://uniswap.org/docs/v2/javascript-SDK/fetching-data/

**Comment by i-schuetz** [comment]
I was able to configure it for Infura:

Add `ethers` as dependency:
```
npm install --save ethers
```
import:
```
import { ethers } from "ethers";
```
Create provider:

```
const provider = new ethers.providers.InfuraProvider();
```
Pass provider to `Fetcher` methods:
```
Fetcher.fetchTokenData(ChainId.MAINNET, address, provider);
```
The Uniswap SDK should document this IMO. It was a bit difficult to figure out.

**Comment by i-schuetz** [comment]
I was able to configure it with Infura:

Add `ethers` as dependency:
```
npm install --save ethers
```
import:
```
import { ethers } from "ethers";
```
Create provider:

```
const network = "homestead";
const infuraProjectId = "...";
const provider = new ethers.providers.InfuraProvider(network, infuraProjectId);
```
Pass provider to `Fetcher` methods:
```
Fetcher.fetchTokenData(ChainId.MAINNET, address, provider);
```
The Uniswap SDK should document this IMO. It was a bit difficult to figure out.

**Comment by LearnPHPaz** [comment]
Oh my bad I forgot to post the solution here. Here is how I did it:

`const myProvider = ethers.getDefaultProvider("homestead", {
    etherscan: "...",
});`

**Comment by moodysalem** [comment]
Fetcher was removed from this repository
