### ISSUE TITLE
Decimal for every token changes.

### ISSUE THREAD

**Issue by lapaz17** [Uniswap/uniswap-v2-sdk#40]
I tried your code. For chainlink 18 decimals(like in your code) works. But for usdt 6, for wbtc 5 and so on...

```typescript
 const usdt= new Token(ChainId.MAINNET, '0xdac17f958d2ee523a2206206994597c13d831ec7', 6, 'USDT', 'Tether USDT');
 const pair = await Fetcher.fetchPairData(usdt, WETH[usdt.chainId]);
 const route = new Route([pair], WETH[usdt.chainId]); //works perfect, but when decimals is 18 it does not.
console.log(route.midPrice.toSignificant(6))
```

What is the reason for that?

**Comment by moodysalem** [comment]
A unit test would be great, but really doubt this is broken given it works in our uniswap/uniswap-interface repo

Anyway Fetcher has been removed from this repo see https://github.com/Uniswap/uniswap-v2-sdk/issues/39#issuecomment-792328760
