### ISSUE TITLE
Bug when running uniswap-sdk in Macos

### ISSUE THREAD

**Issue by trungtaba** [Uniswap/uniswap-v2-sdk#47]
Hello,

When running uniswap-sqk in Macos, I got some errors about library.
So I need to install additional libraries:
- yarn add @ethersproject/providers
- yarn add @ethersproject/contracts
- yarn add @ethersproject/solidity

My environment:
- Macos: 11.0.1
- Node: v12.16.1
- yarn: 1.22.4

**Comment by moodysalem** [comment]
Not a mac bug, you just need to install the peer dependencies
https://nodejs.org/en/blog/npm/peer-dependencies/
