### ISSUE TITLE
iframe integration doesn't work even on own uniswap site (documentation live example)

### ISSUE THREAD

**Issue by sergey-chekriy** [Uniswap/uniswap-v2-sdk#49]
iframe integration doesn't work even on own uniswap site, it should show some real live example in documentation page, see link, but it doesn't, and if you check javascript console, there are few errors.. Will it be fixed eventually? and when..?
https://uniswap.org/docs/v2/interface-integration/iframe-integration/#live-example
link above (official example) works _only_ in Firefox. But doesn't work in chrome/safari/opera

**Comment by moodysalem** [comment]
Not related to the Uniswap SDK, and also it looks like it works now
