### ISSUE TITLE
Waiting for XinFin-XDC Network support in Uniswap

### ISSUE THREAD

**Issue by vrushalipanchal** [Uniswap/uniswap-v2-sdk#51]
Hello Team,

It will be great if Would you consider to Add ETH compatible DPOS chain (XinFin Network) support in Uniswap.

XinFin Digital Contract or XDC — the XinFin network’s native crypto — is a one-stop solution that combines speed, scalability, and sustainability into an immaculate package. XDC is built on XinFin’s exclusive consensus mechanism — the XinFin Delegated Proof-of-Stake or XDPoS protocol that was specially developed to overcome the shortcomings of the technology that came before it.

XinFin Network: https://xdc.network/home
Github:- https://github.com/XinFinOrg/XDPoSChain
CMC :- https://coinmarketcap.com/currencies/xinfin-network/
Circulating Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=getcirculatingsupply
Total Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=totalXDC
Docker FullNode:- https://github.com/xinfinorg/XinFin-Node
Integration Code example: https://xinfin.org/exchange-listing-resource

Technical Community Support available at:

Telegram Community: https://t.me/XinFinDevelopers
Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/
Slack Invitation Link: https://launchpass.com/xinfin-public
Technical help Resource: http://howto.xinfin.org/

Hope you will revert soon.

**Comment by moodysalem** [comment]
Treating all non-Ethereum mainnet/testnet networks as one issue https://github.com/Uniswap/uniswap-v2-sdk/issues/52
