### ISSUE TITLE
Let factory address be provided by package consumer

### ISSUE THREAD

**Issue by wildmolasses** [Uniswap/uniswap-v2-sdk#55]
Awesome work on this sdk!

I use it on a local hardhat-deployed uniswap (factory, routerv02, etc). Currently I have to patch the package in order to set a custom factory address. 

```diff
diff --git a/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js b/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js
index a4450f3..553cfe0 100644
--- a/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js
+++ b/node_modules/@uniswap/sdk/dist/sdk.cjs.development.js
@@ -38,7 +38,7 @@ var _SOLIDITY_TYPE_MAXIMA;
   Rounding[Rounding["ROUND_UP"] = 2] = "ROUND_UP";
 })(exports.Rounding || (exports.Rounding = {}));
 
-var FACTORY_ADDRESS = '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f';
+var FACTORY_ADDRESS = process.env.MODE === 'test' ? '0xe368b31237b833aB46A1B79f06973e383217AbA7' : '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f';
 var INIT_CODE_HASH = '0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f';
 var MINIMUM_LIQUIDITY = /*#__PURE__*/JSBI.BigInt(1000); // exports for internal consumption
```

Would it be possibly to expose the factory address so it can be set to a custom address?

**Comment by moodysalem** [comment]
The only place the factory address is used is here:
https://github.com/Uniswap/uniswap-v2-sdk/blob/6552b384db4355b53c620f6db273aa17ad5913c5/src/entities/pair.ts#L15-L23

We should move that function into a separate exported method, `computePairAddress(factoryAddress: string, tokenA: Token, tokenB: Token)` which is then called by `Pair#getAddress`
