### ISSUE TITLE
ES6/Browser consumption?

### ISSUE THREAD

**Issue by datvm** [Uniswap/uniswap-v2-sdk#57]
Hi anyway I can compile the files for using in browser? With TypeScript if possible but I am okay with a JS file without typing. I tried compiling them using TypeScript myself but was unsuccessful because of import statements like these

```
import JSBI from 'jsbi';
export { default as JSBI } from 'jsbi';
import invariant from 'tiny-invariant';
...
```

**Comment by moodysalem** [comment]
All the files in the repository should be compatible with the browser.
